general {
    lock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")'
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# listener {
#     timeout = 570
#     on-timeout = ddcutil --display 2 getvcp 10
#     on-resume = ddcutil --display 2 getvcp 100
# }

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}